// Auto-generated by OpenLane
module des_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  output[63:0] desc_result,
  output desc_ready,
  input clk,
  input rst_n,
  input des_encipher_en,
  input des_decipher_en,
  input[63:0] des_data,
  input[63:0] des_key_in
);
endmodule
